# Generated by Django 5.0.1 on 2025-07-11 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número de habitación (máximo 4 dígitos)', unique=True, validators=[django.core.validators.MinValueValidator(1, message='El número de habitación debe ser mayor a 0'), django.core.validators.MaxValueValidator(9999, message='El número de habitación no puede tener más de 4 dígitos')])),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('triple', 'Triple'), ('familiar', 'Familiar (4 camas)')], help_text='Tipo de habitación', max_length=20)),
                ('precio_noche', models.DecimalField(decimal_places=2, help_text='Precio por noche en soles', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser mayor a 0')])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('sucio', 'Sucio'), ('mantenimiento', 'En mantenimiento')], default='disponible', help_text='Estado actual de la habitación', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la habitación', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'rooms',
                'ordering': ['numero'],
            },
        ),
    ]
