# Generated by Django 5.0.1 on 2025-07-12 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres del cliente', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos del cliente', max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('pasaporte', 'Pasaporte'), ('carnet_extranjeria', 'Carnet de extranjería')], help_text='Tipo de documento de identidad', max_length=20)),
                ('numero_documento', models.CharField(help_text='Número de documento de identidad', max_length=30)),
                ('numero_habitaciones_deseadas', models.PositiveIntegerField(help_text='Cantidad de habitaciones que desea reservar', validators=[django.core.validators.MinValueValidator(1, message='Debe desear al menos 1 habitación'), django.core.validators.MaxValueValidator(10, message='Máximo 10 habitaciones por reserva')])),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('billetera_digital', 'Billetera digital'), ('visa', 'Visa')], help_text='Tipo de pago seleccionado', max_length=20)),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Monto pagado por el cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El monto debe ser mayor a 0')])),
                ('edad', models.PositiveIntegerField(blank=True, help_text='Edad del cliente', null=True, validators=[django.core.validators.MinValueValidator(1, message='La edad debe ser mayor a 0'), django.core.validators.MaxValueValidator(120, message='La edad debe ser menor a 120 años')])),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos', regex='^\\d{7,15}$')])),
                ('direccion', models.TextField(blank=True, help_text='Dirección del cliente', max_length=200, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, help_text='Fecha y hora de ingreso', null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, help_text='Fecha y hora de salida (máximo 12:00 PM)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente-Habitación',
                'verbose_name_plural': 'Cliente-Habitaciones',
                'db_table': 'client_rooms',
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='unique_documento_client'),
        ),
        migrations.AddField(
            model_name='clientroom',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones_asignadas', to='clients.client'),
        ),
        migrations.AddField(
            model_name='clientroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_asignados', to='rooms.room'),
        ),
        migrations.AddConstraint(
            model_name='clientroom',
            constraint=models.UniqueConstraint(fields=('client', 'room'), name='unique_client_room'),
        ),
    ]
