# Generated by Django 5.0.1 on 2025-07-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fecha_salida_real',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora real de salida (cuando se liberan las habitaciones)', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de salida planeada', null=True),
        ),
    ]
