# Generated by Django 5.0.1 on 2025-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_fecha_salida_real_alter_client_fecha_salida'),
        ('rooms', '0002_alter_room_estado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_documento_client',
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='idx_client_documento'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['fecha_ingreso'], name='idx_client_fecha_ingreso'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['fecha_salida_real'], name='idx_client_fecha_salida_real'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='idx_client_created_at'),
        ),
        migrations.AddIndex(
            model_name='clientroom',
            index=models.Index(fields=['client'], name='idx_clientroom_client'),
        ),
        migrations.AddIndex(
            model_name='clientroom',
            index=models.Index(fields=['room'], name='idx_clientroom_room'),
        ),
        migrations.AddIndex(
            model_name='clientroom',
            index=models.Index(fields=['fecha_asignacion'], name='idx_clientroom_fecha'),
        ),
    ]
