# Generated by Django 5.0.1 on 2025-07-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_unique_documento_client_and_more'),
        ('rooms', '0002_alter_room_estado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientroom',
            name='unique_client_room',
        ),
        migrations.AddField(
            model_name='clientroom',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('liberado', 'Liberado')], default='activo', help_text='Estado de la asignación cliente-habitación', max_length=20),
        ),
        migrations.AddField(
            model_name='clientroom',
            name='fecha_liberacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se liberó esta habitación', null=True),
        ),
        migrations.AddIndex(
            model_name='clientroom',
            index=models.Index(fields=['estado'], name='idx_clientroom_estado'),
        ),
        migrations.AddConstraint(
            model_name='clientroom',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('client', 'room', 'estado'), name='unique_client_room_active'),
        ),
    ]
